name: Mirror Release

on:
  release:
    types: [published]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Set up variables
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "MIRROR_REPO_URL=git@github.com:EkuboProtocol/contracts.git" >> $GITHUB_ENV  # Replace with your mirror repo URL

      - name: Checkout source code at the release tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.RELEASE_TAG }}

      - name: Set up SSH agent and add deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_REPO_DEPLOY_KEY }}

      - name: Checkout mirror repository
        uses: actions/checkout@v3
        with:
          repository: EkuboProtocol/contracts
          path: mirror_repo
          ssh-key: ${{ secrets.MIRROR_REPO_DEPLOY_KEY }}
          fetch-depth: 0

      - name: Prepare files to mirror
        run: |
          rsync -av --delete --prune-empty-dirs \
            --include='.gitignore' \
            --include='.tool-versions' \
            --include='README.md' \
            --include='LICENSE' \
            --include='Scarb.lock' \
            --include='Scarb.toml' \
            --include='src/***' \
            --exclude='src/tests/***' \
            --exclude='src/tests.cairo' \
            --exclude='*' \
            . mirror_repo/

      - name: Modify src/lib.cairo
        run: |
          sed -i '/#\[cfg(test)\]/d' mirror_repo/src/lib.cairo
          sed -i '/pub(crate) mod tests;/d' mirror_repo/src/lib.cairo

      - name: Commit and push changes to mirror repository
        working-directory: mirror_repo
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          # Check if there are any changes
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "mirror $RELEASE_TAG"
            git tag $RELEASE_TAG
            git push origin main --tags
          fi
