name: Mirror

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.MIRRORING_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Clone destination repo
        run: |
          git clone git@github.com:EkuboProtocol/contracts-shareable.git ../mirror

      - name: Copy matching files
        run: |
          find src -name "*.cairo" ! -name "*_test.cairo" ! -name "tests.cairo" ! -name "option_incentives.cairo" ! -path "src/tests/**" | xargs -I '{}' cp --parents '{}' ../mirror/

      - name: Push to destination repo
        run: |
          cd ../mirror
          git add .
          git reset $(git commit-tree HEAD^{tree} -m "mirrored @ ${{ github.sha }}")
          git push -f origin main

