name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Test the code
        run: |
          scarb test
  
  analyzer:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Set up thoth
        run: |
          sudo apt install graphviz
          git clone https://github.com/FuzzingLabs/thoth && cd thoth
          pip install .

      - name: Build the code
        run: |
          scarb build
      
      - name: Run thoth
        run: |
          thoth local target/dev/ekubo_Core.sierra.json -a

