name: Tests

on: [push, pull_request]

env:
  SCARB_VERSION: v0.3.0

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Scarb binary
        uses: actions/cache@v2
        with:
          path: ~/.scarb
          key: scarb-${{ env.SCARB_VERSION }}-${{ runner.os }}
          restore-keys: scarb-${{ env.SCARB_VERSION }}-${{ runner.os }}

      - name: Scarb Setup
        run: |
          if [[ ! -f $HOME/.scarb/bin/scarb ]]; then
            wget https://github.com/software-mansion/scarb/releases/download/${{ env.SCARB_VERSION }}/scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
            mkdir $HOME/.scarb
            tar -xvzf scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu.tar.gz -C $HOME/.scarb --strip-components=1
          fi
          echo "$HOME/.scarb/bin" >> $GITHUB_PATH

      - name: Download cairo
        run: |
          wget https://github.com/starkware-libs/cairo/releases/download/v1.1.0/release-x86_64-unknown-linux-musl.tar.gz
          tar -xvf release-x86_64-unknown-linux-musl.tar.gz

      - name: Update cairo_project
        run: ./scripts/generate_cairo_project.sh

      - name: Scarb Build
        run: scarb build
          
      - name: Test the code
        run: |
          export PATH=$PATH:$(pwd)/cairo/bin
          scarb run test